#ifndef BRUREGS_H
#define BRUREGS_H

#define BRU_REGISTER_BASE 0x20000000ULL
#define BRU_ENABLE_GLOBAL (BRU_REGISTER_BASE + 0x0)
#define BRU_SETTINGS_REG_BASE (BRU_ENABLE_GLOBAL + 0x8)
#define BRU_SETTINGS_COUNT_INSTFETCH (BRU_SETTINGS_REG_BASE)
#define BRU_SETTINGS_EN_WBTHROTTLE (BRU_SETTINGS_REG_BASE + 0x1)
#define BRU_SETTINGS_COUNT_PUTS (BRU_SETTINGS_REG_BASE + 0x2)
#define BRU_SETTINGS_PERIODLEN (BRU_SETTINGS_REG_BASE + 0x8)
#define BRU_ACCESS_BUDGET_REG(n)


enum BRUREGISTER
{
    ENABLE_GLOBAL,
    SETTINGS_COUNT_INST_FETCH,
    SETTINGS_EN_WBTHROTTLE,
    SETTIGNS_COUNT_PUTS,
    PERIOD_LEN,
    READ_ACCESS_BUDGET,
    WRITE_ACCESS_BUDGET,
    WRITEBACK_ACCESS_BUDGET,
    CPU_ENABLE,
    DOMAIN_ASSIGNMENT,
    PERF_ENABLE,
    PERF_PERIOD,
    BANK_READ_COUNTER,
    BANK_WRITE_COUNTER
};





#endif